//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.04 at 10:13:02 PM CEST 
//


package org.malinowsky.appcodewars.text.align.justify.xml.input;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.malinowsky.appcodewars.text.align.justify.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Justify_QNAME = new QName("", "justify");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.malinowsky.appcodewars.text.align.justify.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Justify }
     * 
     */
    public Justify createJustify() {
        return new Justify();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link Inputs }
     * 
     */
    public Inputs createInputs() {
        return new Inputs();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Justify }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "justify")
    public JAXBElement<Justify> createJustify(Justify value) {
        return new JAXBElement<Justify>(_Justify_QNAME, Justify.class, null, value);
    }

}
